### ISSUE TITLE
Deployment is not working anymore after #15

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#19]
Ever since #15 deploying the webapp doesnt work anymore, something must have happened during #11 #12 #13 and #15 (probably when merge conflicts were solved by @Qw3rty26) to the web.xml

Tomcat logs when trying to start ```servlet-1.0```:

```
FAIL - Application at context path [/servlet-1.0] could not be started
FAIL - Encountered exception [org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/servlet-1.0]]]
```

**Comment by San7o** [comment]
It works on my machine
![image](https://github.com/Lenigir-Srl/risto89/assets/81651399/1266a5d1-a5ec-40cf-9f90-86fa43255200)

The problem must be in how It's accessing the resources
