### ISSUE TITLE
Login Manager

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#2]
We should add a login page to risto89, after successful login the user will be granted a session both with urlencoded and cookies.

**Comment by San7o** [comment]
Great suggestion @Qw3rty26 ! Thanks for your issue

To be more clear, we need a new servlet at the "/login" page, a filter to check if the user has a session, an error page. The login will grant a session to the user, and the user can logout with a button. The login will lead to "/profile", only the logged in users will be able to access it.

**Comment by San7o** [comment]
Added issues #3 #4 #5 #6 #7

**Comment by San7o** [comment]
After lots of work, finally the login page is set and ready! Closing this issue
