### ISSUE TITLE
Refactoring styling, top bar and footer

### ISSUE THREAD

**Issue by San7o** [Lenigir-Srl/risto89#45]
In order to keep a consistent look through the whole project, each page should use the same css styling and outsource the same top bar and footer. This way, we would need to change only one file instead of many to make adjustments to the look and functionality of the website, saving us some time

**Comment by Qw3rty26** [comment]
Good idea @San7o!

**Comment by Qw3rty26** [comment]
This would be a little bit tricky @San7o, actually.

Html is by itself a static language so "sourcing"/"including" other bits of html code from another file (e.g. sourcing the "header" code into the `Homepage.html`) wouldn't be easy thing to do.

Workarounds are available, but not suggested <a href="https://stackoverflow.com/questions/7542872/how-to-include-one-html-file-into-another">check this</a>.

<br><br>
The easiest thing to do, would be to turn all the `*.html` into `*.jsp`, that way we could source the code by putting:

`<%@ include page="/source/to/code"%>`

I can do that, but I'm not sure that is what we want. Let me know what you think.

**Comment by San7o** [comment]
It's totally right to change everything from html to jsp. The conversion from jsp to java code will create a little load on the server which can be handled by Tomcat without compromising performance

**Comment by San7o** [comment]
Good job, closing
