### ISSUE TITLE
Ordering the `webapp` directory

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#47]
Files inside `webapp` should be ordered based upon what their purpose is. Three main directories should be created: `Html`, `CSS` and `JavaScript`.
This way our code should be much easier to read.

**Comment by San7o** [comment]
Don't forget jsp

**Comment by Qw3rty26** [comment]
You're right @San7o! Adding the `JSP` directory is also a good idea.

**Comment by Qw3rty26** [comment]
We should make it so that `web.xml` contains all the paths to our pages so that we can use hrefs like `/login` or `/bevande` and not have any problems of path relativity.

**Comment by San7o** [comment]
A note: you should change all the relative paths (starting with `./`) with absolute paths (mapper in `web.xml`)
