### ISSUE TITLE
Asking User to use Cookies

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#73]
Our website currently doesn't ask the user if it can use cookies to store data information.
A small box should be made, informing the user about the consequences of his decision, it should respect the rules listed <a href="https://www.w3.org/TR/csp-cookies/">here</a>

**Comment by Qw3rty26** [comment]
To check if the unsigned user does or does not want cookies we should use a document attribute of type boolean, which can be "T" for "Yes i want to use cookies" or "F" for "No i do not want cookies". The variable should be set to "T" by default.

**Comment by San7o** [comment]
Note: Use localStorage to save user's decision. Local storage should be sent to the server on each request.
The teacher allowed us to use javascript libraries to help the process

**Comment by Qw3rty26** [comment]
Is this done? What's left to do here @San7o ?

**Comment by Qw3rty26** [comment]
This was the last issue, solved by #97. Great Job @San7o !!!!
