### ISSUE TITLE
Choosing the webapp name

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#75]
After our assignment has been analyzed it is easy to say "Risto89" is not a good name for a webapp about Tickets for events in the city of Trento.
Something else should be picked....any Ideas?

**Comment by Qw3rty26** [comment]
I was thinking of "TOMTickets", which stands for "Trento Online Market for Tickets".

**Comment by San7o** [comment]
:face_in_clouds:
