### ISSUE TITLE
Automating dynamic pages

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#8]
A script is needed to ease the transformation of a static html webpage into a dynamic webpage (readable by Java).

The script should take 2 parameters as input, the name of the script itself (e.g. "turn_to_dynamic" and the file to be transformed.
Here's an example of what running the script would look like:

bash:
```>./turn_to_servlet.sh /path/to/file```

- The path where the script saves the new servlet-readable file is yet to be established.
- The script can also be written in any other language

**Comment by San7o** [comment]
Good

**Comment by San7o** [comment]
Script no longer needed as discussed in #16 
Closing
