### ISSUE TITLE
Copyright Infringement!!!!

### ISSUE THREAD

**Issue by riginel** [Lenigir-Srl/risto89#88]
Subject: Notice of Copyright Infringement Regarding Company Name

Dear [Company Name],

I am writing to formally address a matter of copyright infringement that has come to my attention. It has been brought to my notice that your company is using my first name, [Your First Name], albeit in a reversed form, as your company name. This action has created an association between your business and my personal identity, which is both unauthorized and misleading.

The use of my name in this manner suggests an endorsement or affiliation that does not exist, and it infringes upon my personal rights. I have not consented to the use of my name, in any form, for commercial or corporate branding purposes. This infringement is causing confusion among my peers and professional network, and it is affecting my personal brand and reputation.

I request that you cease the use of my reversed name as your company name immediately. Failure to comply with this request will leave me no choice but to pursue all legal avenues to protect my rights and interests.

Please respond to this letter within [number of days] days to confirm that you will take the necessary steps to rectify this situation.

Sincerely,
[Your Full Name]
[Your Contact Information]

**Comment by Tech-Matt** [comment]
I agree

**Comment by Qw3rty26** [comment]
Dear [Your First Name]


we dont care

**Comment by Qw3rty26** [comment]
Dear [Your First Name]

after a full day of not caring about your comment, i've decided its time to close this issue with this comment.



Don't you ever create an issue in this repo ever again, or else.


Best reguard


- The Lenigir Srl Team
