### ISSUE TITLE
Add target/ to .gitignore

### ISSUE THREAD

**Issue by San7o** [Lenigir-Srl/risto89#9]
**What am I proposing?**
Adding the target directory to the .gitignore file so that Its contents won't be pushed upstream

**Are you willing to solve this issue?**
Yes

**Comment by Qw3rty26** [comment]
```target/``` added to .gitignore with pull request #11 
Closing...

**Comment by Qw3rty26** [comment]
After adding ```target/``` to ```.gitignore``` it is wise to run:

```shell
git rm -r --cached target/
``` 

PR will be made to apply the changes....
